// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include "L0.h"
#include "L1.h"
#include "L2.h"

// Combos definition
enum combos {
  X_COMBO,
  V_COMBO,
  J_COMBO,
  L_COMBO,
  U_COMBO,
  R_COMBO,
  C_COMBO,
  K_COMBO,
  Q_COMBO,
  Z_COMBO,
  Y_COMBO,
  H_COMBO,
  S_COMBO,
  D_COMBO,
  LEFT_ANGLE_BRACKET_COMBO,
  RIGHT_ANGLE_BRACKET_COMBO,
  LEFT_BRACKET_COMBO,
  RIGHT_BRACKET_COMBO,
  LEFT_CURLY_BRACE_COMBO,
  RIGHT_CURLY_BRACE_COMBO,
  LEFT_PAREN_COMBO,
  RIGHT_PAREN_COMBO,
  F4_COMBO,
  F5_COMBO,
  F6_COMBO,
  F7_COMBO,
  F8_COMBO,
  F9_COMBO,
  N3_COMBO,
  N4_COMBO,
  N5_COMBO,
  N6_COMBO,
  COMBO_COUNT
};
uint16_t COMBO_LEN = COMBO_COUNT;

combo_t key_combos[COMBO_COUNT] = {
  // Left Alpha
  [X_COMBO] = COMBO(L0L0_L0L1_combo, KC_X),
  [V_COMBO] = COMBO(L0L1_L0L2_combo, KC_V),
  [J_COMBO] = COMBO(L0L0_L0L2_combo, KC_J),
  [L_COMBO] = COMBO(L0L3_L0L4_combo, KC_L),
  [U_COMBO] = COMBO(L0L4_L0L5_combo, KC_U),
  [R_COMBO] = COMBO(L0L3_L0L5_combo, KC_R),
  [C_COMBO] = COMBO(L0L3_L0L4_L0L5_combo, KC_C),
  // Right Alpha
  [K_COMBO] = COMBO(L0R0_L0R1_combo, KC_K),
  [Q_COMBO] = COMBO(L0R1_L0R2_combo, KC_Q),
  [Z_COMBO] = COMBO(L0R0_L0R2_combo, KC_Z),
  [Y_COMBO] = COMBO(L0R3_L0R4_combo, KC_Y),
  [H_COMBO] = COMBO(L0R4_L0R5_combo, KC_H),
  [S_COMBO] = COMBO(L0R3_L0R5_combo, KC_S),
  [D_COMBO] = COMBO(L0R3_L0R4_L0R5_combo, KC_D),
  // Symbols
  [LEFT_ANGLE_BRACKET_COMBO] = COMBO(L1L0_L1L1_combo, KC_LEFT_ANGLE_BRACKET),
  [RIGHT_ANGLE_BRACKET_COMBO] = COMBO(L1L1_L1L2_combo, KC_RIGHT_ANGLE_BRACKET),
  [LEFT_BRACKET_COMBO] = COMBO(L1L3_L1L4_combo, KC_LEFT_BRACKET),
  [RIGHT_BRACKET_COMBO] = COMBO(L1L4_L1L5_combo, KC_RIGHT_BRACKET),
  [LEFT_CURLY_BRACE_COMBO] = COMBO(L1R0_L1R1_combo, KC_LEFT_CURLY_BRACE),
  [RIGHT_CURLY_BRACE_COMBO] = COMBO(L1R1_L1R2_combo, KC_RIGHT_CURLY_BRACE),
  [LEFT_PAREN_COMBO] = COMBO(L1R3_L1R4_combo, KC_LEFT_PAREN),
  [RIGHT_PAREN_COMBO] = COMBO(L1R4_L1R5_combo, KC_RIGHT_PAREN),
  // Fn
  [F4_COMBO] = COMBO(L2L0_L2L1_combo, KC_F4),
  [F5_COMBO] = COMBO(L2L1_L2L2_combo, KC_F5),
  [F6_COMBO] = COMBO(L2L0_L2L2_combo, KC_F6),
  [F7_COMBO] = COMBO(L2L3_L2L4_combo, KC_F7),
  [F8_COMBO] = COMBO(L2L4_L2L5_combo, KC_F8),
  [F9_COMBO] = COMBO(L2L3_L2L5_combo, KC_F9),
  // Nums
  [N5_COMBO] = COMBO(L2R0_L2R1_combo, KC_5),
  [N6_COMBO] = COMBO(L2R1_L2R2_combo, KC_6),
  [N3_COMBO] = COMBO(L2R3_L2R4_combo, KC_3),
  [N4_COMBO] = COMBO(L2R4_L2R5_combo, KC_4),
};
