// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include "L0.h"
#include "L1.h"
#include "L2.h"

// Combos definition
enum combos {
  X_COMBO,
  V_COMBO,
  J_COMBO,
  L_COMBO,
  U_COMBO,
  R_COMBO,
  C_COMBO,
  K_COMBO,
  Q_COMBO,
  Z_COMBO,
  Y_COMBO,
  H_COMBO,
  S_COMBO,
  D_COMBO,
  LEFT_ANGLE_BRACKET_COMBO,
  RIGHT_ANGLE_BRACKET_COMBO,
  LEFT_BRACKET_COMBO,
  RIGHT_BRACKET_COMBO,
  LEFT_CURLY_BRACE_COMBO,
  RIGHT_CURLY_BRACE_COMBO,
  LEFT_PAREN_COMBO,
  RIGHT_PAREN_COMBO,
  F4_COMBO,
  F5_COMBO,
  F6_COMBO,
  F7_COMBO,
  F8_COMBO,
  F9_COMBO,
  N3_COMBO,
  N4_COMBO,
  N5_COMBO,
  N6_COMBO,
  COMBO_COUNT
};
uint16_t COMBO_LEN = COMBO_COUNT;

combo_t key_combos[COMBO_COUNT] = {
  // Left Alpha
  [X_COMBO] = COMBO(LTR0_LTM0_combo, KC_X),
  [V_COMBO] = COMBO(LTM0_LTI0_combo, KC_V),
  [J_COMBO] = COMBO(LTR0_LTI0_combo, KC_J),
  [L_COMBO] = COMBO(LHR0_LHM0_combo, KC_L),
  [U_COMBO] = COMBO(LHM0_LHI0_combo, KC_U),
  [R_COMBO] = COMBO(LHR0_LHI0_combo, KC_R),
  [C_COMBO] = COMBO(LHR0_LHM0_LHI0_combo, KC_C),
  // Right Alpha
  [K_COMBO] = COMBO(RTI0_RTM0_combo, KC_K),
  [Q_COMBO] = COMBO(RTM0_RTR0_combo, KC_Q),
  [Z_COMBO] = COMBO(RTI0_RTR0_combo, KC_Z),
  [Y_COMBO] = COMBO(RHI0_RHM0_combo, KC_Y),
  [H_COMBO] = COMBO(RHM0_RHR0_combo, KC_H),
  [S_COMBO] = COMBO(RHI0_RHR0_combo, KC_S),
  [D_COMBO] = COMBO(RHI0_RHM0_RHR0_combo, KC_D),
  // Symbols
  [LEFT_ANGLE_BRACKET_COMBO] = COMBO(LTR1_LTM1_combo, KC_LEFT_ANGLE_BRACKET),
  [RIGHT_ANGLE_BRACKET_COMBO] = COMBO(LTM1_LTI1_combo, KC_RIGHT_ANGLE_BRACKET),
  [LEFT_BRACKET_COMBO] = COMBO(LHR1_LHM1_combo, KC_LEFT_BRACKET),
  [RIGHT_BRACKET_COMBO] = COMBO(LHM1_LHI1_combo, KC_RIGHT_BRACKET),
  [LEFT_CURLY_BRACE_COMBO] = COMBO(RTI1_RTM1_combo, KC_LEFT_CURLY_BRACE),
  [RIGHT_CURLY_BRACE_COMBO] = COMBO(RTM1_RTR1_combo, KC_RIGHT_CURLY_BRACE),
  [LEFT_PAREN_COMBO] = COMBO(RHI1_RHM1_combo, KC_LEFT_PAREN),
  [RIGHT_PAREN_COMBO] = COMBO(RHM1_RHR1_combo, KC_RIGHT_PAREN),
  // Fn
  [F4_COMBO] = COMBO(LTR2_LTM2_combo, KC_F4),
  [F5_COMBO] = COMBO(LTM2_LTI2_combo, KC_F5),
  [F6_COMBO] = COMBO(LTR2_LTI2_combo, KC_F6),
  [F7_COMBO] = COMBO(LHR2_LHM2_combo, KC_F7),
  [F8_COMBO] = COMBO(LHM2_LHI2_combo, KC_F8),
  [F9_COMBO] = COMBO(LHR2_LHI2_combo, KC_F9),
  // Nums
  [N5_COMBO] = COMBO(RTI2_RTM2_combo, KC_5),
  [N6_COMBO] = COMBO(RTM2_RTR2_combo, KC_6),
  [N3_COMBO] = COMBO(RHI2_RHM2_combo, KC_3),
  [N4_COMBO] = COMBO(RHM2_RHR2_combo, KC_4),
};
