// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#define LTP1 KC_LEFT_ANGLE_BRACKET
#define LTR1 LSFT_T(KC_GRAVE)
#define LTM1 LCTL_T(KC_BACKSLASH)
#define LTI1 LALT_T(KC_UNDERSCORE)
#define LTJ1 KC_RIGHT_ANGLE_BRACKET
#define LHP1 KC_LEFT_BRACKET
#define LHR1 KC_HASH
#define LHM1 KC_DOLLAR
#define LHI1 KC_AMPERSAND
#define LHJ1 KC_RIGHT_BRACKET
#define LBR1 KC_EXCLAIM
#define LBM1 KC_AT
#define LBI1 KC_NO
#define LT01 TO(1)
#define LT11 KC_TAB

#define RT11 KC_LGUI
#define RT01 TO(0)
#define RBI1 KC_COLON
#define RBM1 KC_SEMICOLON
#define RBR1 KC_QUESTION
#define RHJ1 KC_LEFT_PAREN
#define RHI1 KC_DOT
#define RHM1 KC_COMMA
#define RHR1 KC_QUOTE
#define RHP1 KC_RIGHT_PAREN
#define RTJ1 KC_LEFT_CURLY_BRACE
#define RTI1 RSFT_T(KC_MINUS)
#define RTM1 RCTL_T(KC_SLASH)
#define RTR1 RALT_T(KC_EQUAL)
#define RTP1 KC_RIGHT_CURLY_BRACE

// KC_CIRCUMFLEX
// KC_PIPE
// KC_UNDERSCORE
// KC_PLUS
// KC_ASTERISK
// KC_PERCENT