// Copyright 2023 Roming22 (@Roming22)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define COMBO_STRICT_TIMER
#define COMBO_TERM 40

// #define HOLD_ON_OTHER_KEY_PRESS
#define PERMISSIVE_HOLD
#define TAPPING_TERM 250

#define RGBLIGHT_DEFAULT_HUE 0
#define RGBLIGHT_DEFAULT_SAT 255
#define RGBLIGHT_DEFAULT_VAL 200
#define RGBLIGHT_LAYERS
#define RGBLIGHT_MAX_LAYERS 10
