// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later



#define LTR4 KC_MEDIA_PLAY_PAUSE
#define LTM4 KC_MEDIA_PREV_TRACK
#define LTI4 KC_MEDIA_NEXT_TRACK
#define LHP4 KC_NO
#define LHR4 KC_AUDIO_MUTE
#define LHM4 KC_AUDIO_VOL_DOWN
#define LHI4 KC_AUDIO_VOL_UP
#define LC04 KC_NO
#define LC14 KC_NO

#define RC14 LGUI(KC_GRAVE)
#define RC04 LSG(KC_GRAVE)
#define RHI4 LSG(KC_LEFT)
#define RHM4 LGUI(LCTL(KC_DOWN))
#define RHR4 LSG(KC_RIGHT)
#define RHP4 LGUI(KC_UP)
#define RTI4 LGUI(KC_PAGE_UP)
#define RTM4 LGUI(LCTL(KC_UP))
#define RTR4 LGUI(KC_PAGE_DOWN)
