// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#define LTR4 LGUI(KC_GRAVE)
#define LTM4 LGUI(KC_PAGE_UP)
#define LTI4 LSG(KC_GRAVE)
#define LHP4 KC_NO
#define LHR4 LGUI(LCTL(KC_TAB))
#define LHM4 LGUI(KC_PAGE_DOWN)
#define LHI4 LGUI(KC_TAB)

#define RC14 KC_MEDIA_PREV_TRACK
#define RC04 KC_MEDIA_NEXT_TRACK
#define RHI4 LSG(KC_LEFT)
#define RHM4 LGUI(LCTL(KC_DOWN))
#define RHR4 LSG(KC_RIGHT)
#define RHP4 LGUI(KC_UP)
#define RTI4 KC_AUDIO_VOL_DOWN
#define RTM4 LGUI(LCTL(KC_UP))
#define RTR4 KC_AUDIO_VOL_UP
